title: Talk Academy
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 3

navigation:
 - title: Home
   url: /index.html
 - title: Sobre
   url: /sobre
 - title: Contato
   url: /contato

social:
   github: cmoretti01
   twitter: caiom_paladin
   facebook: caio.marques.12382923
   email: talkacademybr@gmail.com

google_analytics: "UA-58263416-1"
